on: [push, pull_request]
name: Lints on nightly toolchain
jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      RUSTDOCFLAGS: "-Z unstable-options --no-run --no-capture --test-builder clippy-driver"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Check Clippy lints (default features)
        run: cargo clippy --verbose --all
      - name: Check Clippy lints (no default features)
        run: cargo clippy --verbose --all --no-default-features
      - name: Check Clippy lints (all features)
        run: cargo clippy --verbose --all --all-features

      - name: Check Clippy lints (debug feature)
        run: cargo clippy --verbose --all --no-default-features --features=debug
      - name: Check Clippy lints (delta feature)
        run: cargo clippy --verbose --all --no-default-features --features=delta
      - name: Check Clippy lints (get-size2 feature)
        run: cargo clippy --verbose --all --no-default-features --features=get-size2
      - name: Check Clippy lints (serde feature)
        run: cargo clippy --verbose --all --no-default-features --features=serde

      - name: Check Clippy lints on tests (default features)
        run: cargo clippy --verbose --all --tests
      - name: Check Clippy lints on tests (all features)
        run: cargo clippy --verbose --all --tests --all-features

      - name: Check Clippy lints on doctests (default features)
        run: cargo test --verbose --doc
      - name: Check Clippy lints on doctests (all features)
        run: cargo test --verbose --doc --all-features
