on: [push, pull_request]
name: Build documentation on nightly toolchain
jobs:
  rustdoc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings --cfg docsrs -Z unstable-options --generate-link-to-definition"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - name: Build documentation
        run: cargo doc --verbose --features=debug,delta,get-size2,serde --no-deps
